/************************************************************************************
 *
 * Module: Ultra-sonic
 *
 * File Name: ultrasonic.c
 *
 * Description: Header file for the ULTRASONIC driver
 *
 * Author: Omar Hossam ElDin
 *
 ***********************************************************************************/

#include "ultrasonic.h"
#include "icu.h"
#include  "gpio.h"
#include "common_macros.h"
#include <util/delay.h>

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
uint8 g_edgeCount = 0;
uint16 g_time = 0;
uint16 g_distance = 0;

/*******************************************************************************
 *                      Functions Definitions                                   *
 *******************************************************************************/
/*
 * Description : Function to initialize the Ultra-sonic driver
 * 	Setup the call back function
 * 	Configure the trigger pin as an output pin
 */
void Ultrasonic_init(void)
{
	/* Initializing the icu with rising edge and F_CPU/8*/
	Icu_ConfigType IcuConfig={F_CPU_8,RISING_EDGE};
	Icu_init(&IcuConfig);
	/*set the call back function to Ultrasonic_edgeProcessing function */
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	/*Configure PB5 as an output pin for the trigger signal*/
	GPIO_setupPinDirection(PORTB_ID,PIN5_ID,PIN_OUTPUT);

}

/*
 * Description : send trigger pulse to ultra-sonic
 *
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_LOW);
}

/*
 * Description : end the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment
 *
 */
uint16 Ultrasonic_readDistance(void)
{

	Ultrasonic_Trigger();
	if(g_edgeCount == 2)
	{
	g_distance =  g_time*0.017;
	g_edgeCount = 0;

	}
	return g_distance;
}

/*
 * Description:This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by
 * the ultra-sonic sensor
 *
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING_EDGE);

	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value (T1) */
		g_time = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING_EDGE);

	}

	}

