/************************************************************************************
 *
 * Module: Ultra-sonic
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the ULTRASONIC driver
 *
 * Author: Omar Hossam ElDin
 *
 ***********************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/
/*
 * Description : Function to initialize the Ultra-sonic driver
 * 	Setup the call back function
 * 	Configure the trigger pin as an output pin
 */
void Ultrasonic_init(void);
/*
 * Description : send trigger pulse to ultra-sonic
 *
 */
void Ultrasonic_Trigger(void);
/*
 * Description : end the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment
 *
 */
uint16 Ultrasonic_readDistance(void);
/*
 * Description:This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by
 * the ultra-sonic sensor
 *
 */
void Ultrasonic_edgeProcessing(void);



#endif /* ULTRASONIC_H_ */
